---
apiVersion: apps/v1
kind: Deployment
metadata:
      name: nginx-deployment
      labels:
          app: nginx-app
spec:
    replicas: 1
    selector:
       matchLabels:
            app: nginx-app
    template:
       metadata:
         labels:
           app: nginx-app
       spec:
          containers:
          - name: nginx-container
            image: nginx
            volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
            ports:
            - containerPort: 80
          volumes:
          - name: html
            gitRepo:
              repository: https://github.com/sugreevudu/kubernetes.git
              revision: master
              directory: .            
