---
apiVersion: v1
kind: Service
metadata:
    name: my-service
    labels:
       app: nginx-app
spec:
   selector:
      app: nginx-app
     # app: nginx-ram
   type: NodePort
   ports:
   - nodePort: 32002
     port: 80
     targetPort: 80
